spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diet_app?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
    username: diet_user
    password: diet_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true     # 実行されるSQLをコンソールに出力
    defer-datasource-initialization: true # Hibernateのテーブル生成後にdata.sqlを実行する設定
  sql:
    init:
      mode: always # 常にSQLスクリプトを実行