spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diet_app?useSSL=false&serverTimezone=Asia/Tokyo&allowPublicKeyRetrieval=true
    username: diet_user
    password: diet_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # エンティティ（@Entity）から自動でテーブルを作成・更新
    show-sql: true     # 実行されるSQLをコンソールに出力
    properties:
      hibernate:
        format_sql: true